import type {Metadata} from "next";
import "./globals.css";
import styles from "./layout.module.scss";
import {Header} from "@/components/Header/Header";
import {Footer} from "@/components/Footer/Footer";
import {ReduxProvider} from "@/components/support/ReduxProvider";
import {Alert} from "@/components/wigets/Alert";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={styles.page}>
        <ReduxProvider>
            <Header/>
            <main className={styles.mainContent}>
                {children}
            </main>
            <Footer/>
            <Alert/>
        </ReduxProvider>
        </body>
        </html>
    );
};
